### ISSUE TITLE
Error: The PDB file "complex_cavity_decoy.pdb" did not contain any valid atoms

### ISSUE THREAD

**Issue by areyesromero** [atfrank/RNACavityMiner#1]
Dear developers, 

I have installed RNACavityMiner on a Linux-64 Ubuntu workstation. These are the prerequisites vs what I have: 
**GCC 8.2.0**: 9.3.0
**openbabel**: not installed as it is not supported in Python v3.8
**RxDock**: 0.1.0
**PyMOL**: 2.4.0, educational licensed. 
 **environment.yml**: installed without problems with anaconda. 

From what I have understood I have encountered two errors while running the commands  "./../src/miner_grid.sh 1ANR_1.pdb" in the test folder:

**1) Error: The PDB file "complex_cavity_decoy.pdb" did not contain any valid atoms
2) FileNotFoundError: [Errno 2] No such file or directory: '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/predicted_cavities.txt'**

Any idea how to work around the issue?

Find below the full terminal output:

removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/features.csv'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/complex_cavity_decoy.pdb'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/receptor.pdb'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/cavity_decoy.xyz'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/receptor_grid.xyz'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/receptor_grid.pdb'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/1ANR_1.pdb'
removed '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/receptor.log'
removed directory '/home/atilio/RNA/RNACavityMiner/test/1ANR_1'
'1ANR_1.pdb' -> '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/./1ANR_1.pdb'
started making grids..
 PyMOL not running, entering library mode (experimental)
finished making grids..
started converting coordinate file to MOL2..
finished converting coordinate file to MOL2..
started determining center..
finished determining center..
preparting to featurize..
sed: can't read cavity_decoy.pdb: No such file or directory
sed: can't read cavity_decoy.pdb: No such file or directory
grep: cavity_decoy.pdb: No such file or directory
started featurizing..

Error: The PDB file "complex_cavity_decoy.pdb" did not contain any valid atoms

processing features..
cat: raw_feature.txt: No such file or directory
now estimating ligandability..
cat: /home/atilio/RNA/RNACavityMiner/test/1ANR_1/predicted_cavities.txt: No such file or directory
starting to prune grids
 PyMOL not running, entering library mode (experimental)
Traceback (most recent call last):
  File "/home/atilio/RNA/RNACavityMiner/py/grid_pruner.py", line 74, in <module>
    prune_grid(rna = "receptor", score_file = a.score_in, outname = a.coord_out, quantile = 0.95, sasa_cutoff = 10.0)
  File "/home/atilio/RNA/RNACavityMiner/py/grid_pruner.py", line 36, in prune_grid
    df = pd.read_csv(score_file, header = 0, sep = ",")
  File "/home/atilio/anaconda3/envs/cavityminer/lib/python3.8/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/atilio/anaconda3/envs/cavityminer/lib/python3.8/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/atilio/anaconda3/envs/cavityminer/lib/python3.8/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/home/atilio/anaconda3/envs/cavityminer/lib/python3.8/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/atilio/anaconda3/envs/cavityminer/lib/python3.8/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 361, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 653, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/atilio/RNA/RNACavityMiner/test/1ANR_1/predicted_cavities.txt'

**Comment by atfrank** [comment]
This is most likely an issue with the installation of dependencies. I've updated the install instructions. Please re-try. I've pasted them below for your convenience.

# create environment
```
conda create -n rnacavityminertest -y
conda activate rnacavityminertest

# Install dependencies
conda install -c schrodinger pymol -y
conda install -c conda-forge openbabel
conda install -c bioconda rxdock -y
conda install pandas

pip install --user --force scikit-learn==0.22.2.post1
pip install --user --force xgboost==0.90 
```
# Clone RNACavityMiner
```
git clone https://github.com/atfrank/RNACavityMiner.git
cd RNACavityMiner/
```
	
# Clone RNAPosers
```
git clone https://github.com/atfrank/RNAPosers.git
cd RNAPosers/
make clean
make
cd ..
cp RNAPosers/bin/featurize bin/
rm -rf RNAPosers
```

# Then test with:
```
export CAVITYMINER="/Users/aaronfranklab/RNACavityMiner" # you'll need to change
cd test/
./../src/miner_grid.sh 1ANR_1.pdb
```

**Comment by atfrank** [comment]
@areyesromero based on our offline correspondence, it seems as if the problem has been solved with my latest update to the rego. After addressing installation issues, the remaining issue was that the decimal separator in awk in your locale was "," vs ".". This was resulting in an error when you reading in and operating on the data with Pandas in Python. I'm closing this issue.
